---
AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance

Parameters:
  InstanceName:
    Description: 
    Type: String
    Default: EC2
    Description: Nome da instancia

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b898040803850657
      InstanceType: t2.micro
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
      - Key: Name
        Value: !Ref InstanceName

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref IamRole

  IamRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"